version: '3.3'
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - '8080:8080'
    volumes:
      - /etc/sterlingpdf/trainingdata:/usr/share/tessdata/
      - /etc/sterlingpdf/extraConfigs:/configs/
      - /etc/sterlingpdf/customFiles:/customFiles/
      - /etc/sterlingpdf/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
