global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
# add apps here
  - job_name: 'appname' # add the app to monitor
    static_configs:
      - targets: ['address:port']
    fallback_scrape_protocol: 'PrometheusText0.0.4' # fallback in case metrics != HTML
