# work in progress - not yet ready for deployment
services:
    grafana:
        container_name: grafana
        image: grafana/grafana-oss
        restart: unless-stopped
        ports:
            - '3000:3000/tcp'
        volumes:
            - grafana-data:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=your_password
        networks:
          - monitoring
        depends_on:
          - prometheus

    prometheus:
        container_name: prometheus
        image: bitnami/prometheus
        restart: unless-stopped
        volumes:
            - prometheus-data:/opt/bitnami/prometheus/data
            - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
        ports:
            - '9090:9090/tcp'
        networks:
          - monitoring
volumes:
    grafana-data:
    prometheus-data:

networks:
  monitoring:
